-- Google Sheets publication state and coalescing queue.

-- Some deployments use the legacy host_user_id column without having the
-- original users table in their migration history. Keep this migration
-- self-contained so organizer OAuth has a stable local user record to attach
-- to. Existing users tables are left untouched apart from the auth link below.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users
  add column if not exists auth_user_id uuid unique;

-- Existing tournaments use host_user_id = 1 by default. Seed that compatibility
-- record only when the table is newly empty; real organizer email is stored by
-- the OAuth callback after sign-in.
insert into public.users (id, email)
overriding system value
select 1, 'legacy-host@tftourney.local'
where not exists (select 1 from public.users);

create table if not exists public.organizer_google_connections (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null unique references public.users(id) on delete cascade,
  google_email text,
  scopes text[] not null default '{}',
  encrypted_refresh_token text,
  status text not null default 'connected'
    check (status in ('connected', 'needs_reauth', 'disconnected')),
  last_error_code text,
  last_error_message text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  tournament_id_type text;
begin
  if to_regclass('public.tournament_sheet_exports') is null then
    select format_type(a.atttypid, a.atttypmod)
    into tournament_id_type
    from pg_attribute a
    where a.attrelid = 'public.tournaments'::regclass
      and a.attname = 'id'
      and not a.attisdropped;

    if tournament_id_type is null then
      raise exception 'public.tournaments.id is required before Google Sheets exports can be installed.';
    end if;

    execute format($sql$
      create table public.tournament_sheet_exports (
        id uuid primary key default gen_random_uuid(),
        tournament_id %s not null unique references public.tournaments(id) on delete cascade,
        host_user_id bigint not null default 1,
        spreadsheet_id text unique,
        spreadsheet_url text,
        players_sheet_id integer,
        scores_sheet_id integer,
        checkmate_sheet_id integer,
        state text not null default 'queued'
          check (state in ('queued', 'syncing', 'ready', 'error', 'needs_reauth')),
        desired_revision bigint not null default 1 check (desired_revision >= 0),
        synced_revision bigint not null default 0 check (synced_revision >= 0),
        dirty_at timestamptz not null default now(),
        last_synced_at timestamptz,
        next_attempt_at timestamptz,
        retry_count integer not null default 0 check (retry_count >= 0),
        lease_until timestamptz,
        last_error_code text,
        last_error_message text,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        constraint tournament_sheet_exports_revision_order check (synced_revision <= desired_revision)
      )
    $sql$, tournament_id_type);
  end if;
end $$;

create index if not exists tournament_sheet_exports_claim_idx
  on public.tournament_sheet_exports(state, next_attempt_at, dirty_at);

-- These tables are accessed by the server/worker with the service role. Do not
-- expose organizer refresh tokens or export leases through the public REST API.
alter table public.organizer_google_connections enable row level security;
alter table public.tournament_sheet_exports enable row level security;

drop trigger if exists organizer_google_connections_set_updated_at on public.organizer_google_connections;
create trigger organizer_google_connections_set_updated_at
before update on public.organizer_google_connections
for each row execute function public.set_updated_at();

drop trigger if exists tournament_sheet_exports_set_updated_at on public.tournament_sheet_exports;
create trigger tournament_sheet_exports_set_updated_at
before update on public.tournament_sheet_exports
for each row execute function public.set_updated_at();

create or replace function public.mark_tournament_sheet_export_dirty()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
  tournament_key text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;

  if tg_table_name = 'tournaments' then
    tournament_key := row_data ->> 'id';
  elsif tg_table_name in ('tournament_registrations', 'tournament_participants', 'rounds', 'tournament_edges') then
    tournament_key := row_data ->> 'tournament_id';
  elsif tg_table_name = 'lobbies' then
    select rounds.tournament_id::text into tournament_key
    from public.rounds
    where rounds.id::text = row_data ->> 'round_id';
  elsif tg_table_name = 'lobby_participants' then
    select rounds.tournament_id::text into tournament_key
    from public.lobbies
    join public.rounds on rounds.id = lobbies.round_id
    where lobbies.id::text = row_data ->> 'lobby_id';
  elsif tg_table_name = 'participant_round_scores' then
    select participants.tournament_id::text into tournament_key
    from public.tournament_participants participants
    where participants.id = (row_data ->> 'participant_id')::uuid;
  end if;

  if tournament_key is not null then
    update public.tournament_sheet_exports
    set desired_revision = desired_revision + 1,
        state = case when state = 'syncing' then state else 'queued' end,
        dirty_at = now(),
        next_attempt_at = null,
        last_error_code = null,
        last_error_message = null
    where tournament_id::text = tournament_key;
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'tournaments',
    'tournament_registrations',
    'tournament_participants',
    'rounds',
    'tournament_edges',
    'lobbies',
    'lobby_participants',
    'participant_round_scores'
  ] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_sheet_export_dirty', table_name);
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.mark_tournament_sheet_export_dirty()',
      table_name || '_sheet_export_dirty', table_name
    );
  end loop;
end $$;

create or replace function public.claim_tournament_sheet_exports(p_limit integer default 10)
returns setof public.tournament_sheet_exports
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select exports.id
    from public.tournament_sheet_exports exports
    where (
      exports.state = 'queued'
      or (exports.state = 'syncing' and exports.lease_until < now())
    )
    and coalesce(exports.next_attempt_at, now()) <= now()
    order by exports.dirty_at asc, exports.id asc
    limit greatest(p_limit, 1)
    for update skip locked
  )
  update public.tournament_sheet_exports exports
  set state = 'syncing',
      lease_until = now() + interval '5 minutes',
      updated_at = now()
  from candidates
  where exports.id = candidates.id
  returning exports.*;
end;
$$;

create or replace function public.complete_tournament_sheet_export(
  p_export_id uuid,
  p_revision bigint,
  p_spreadsheet_id text,
  p_spreadsheet_url text,
  p_players_sheet_id integer,
  p_scores_sheet_id integer,
  p_checkmate_sheet_id integer
)
returns public.tournament_sheet_exports
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.tournament_sheet_exports;
begin
  update public.tournament_sheet_exports
  set spreadsheet_id = p_spreadsheet_id,
      spreadsheet_url = p_spreadsheet_url,
      players_sheet_id = p_players_sheet_id,
      scores_sheet_id = p_scores_sheet_id,
      checkmate_sheet_id = p_checkmate_sheet_id,
      synced_revision = greatest(synced_revision, p_revision),
      state = case when desired_revision > p_revision then 'queued' else 'ready' end,
      last_synced_at = case when desired_revision <= p_revision then now() else last_synced_at end,
      lease_until = null,
      retry_count = 0,
      next_attempt_at = null,
      last_error_code = null,
      last_error_message = null,
      updated_at = now()
  where id = p_export_id
  returning * into result;
  return result;
end;
$$;

create or replace function public.fail_tournament_sheet_export(
  p_export_id uuid,
  p_error_code text,
  p_error_message text,
  p_retryable boolean default true
)
returns public.tournament_sheet_exports
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.tournament_sheet_exports;
begin
  update public.tournament_sheet_exports
  set state = case when p_error_code = 'GOOGLE_REAUTH_REQUIRED' then 'needs_reauth' when p_retryable then 'queued' else 'error' end,
      retry_count = retry_count + case when p_retryable then 1 else 0 end,
      next_attempt_at = case when p_retryable then now() + least(interval '15 minutes', interval '5 seconds' * power(2, least(retry_count, 8))) else null end,
      lease_until = null,
      last_error_code = left(p_error_code, 120),
      last_error_message = left(p_error_message, 1000),
      updated_at = now()
  where id = p_export_id
  returning * into result;
  return result;
end;
$$;

revoke execute on function public.claim_tournament_sheet_exports(integer) from public, anon, authenticated;
revoke execute on function public.complete_tournament_sheet_export(uuid, bigint, text, text, integer, integer, integer) from public, anon, authenticated;
revoke execute on function public.fail_tournament_sheet_export(uuid, text, text, boolean) from public, anon, authenticated;
grant execute on function public.claim_tournament_sheet_exports(integer) to service_role;
grant execute on function public.complete_tournament_sheet_export(uuid, bigint, text, text, integer, integer, integer) to service_role;
grant execute on function public.fail_tournament_sheet_export(uuid, text, text, boolean) to service_role;
